spring:
  datasource:
    password: team2020PERU
    url: jdbc:mysql://db-haya-vuelve.cg73jp9y7oht.us-east-2.rds.amazonaws.com:3306/hayavuelve_test
    username: admin
server:
  port: 9091
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
swagger:
  base:
    package:
      name: com.soaint.api.rest.message.rest.controller